// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: postInfo.proto

package cn.tansorflow.server.protocol;

public interface ClientInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serverInfo = 1;</code>
   * @return The serverInfo.
   */
  java.lang.String getServerInfo();
  /**
   * <code>string serverInfo = 1;</code>
   * @return The bytes for serverInfo.
   */
  com.google.protobuf.ByteString
      getServerInfoBytes();

  /**
   * <code>string key = 2;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 2;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
