// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: postInfo.proto

package cn.tansorflow.server.protocol;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
